= Documentation
:author: Jorge Franco
:email: grooscript@gmail.com
:source-highlighter: pygments
:icons: font

=== Introduction

Be aware javascript isn't Java or Groovy, lot of differences between them. The main idea of this project is use
Groovy strength in the browser, not create a full conversion. I'm looking for use groovy code and tools in the client,
wanna use Spock tests in the server and in the browser.

So, for converting your groovy code, you need link:jars/grooscript-0.6.1.jar[grooscript.jar]. You can get from mavenCentral
(org.grooscript:grooscript:0.6.1) in your project's dependencies. Remember need grooscript.js, inside the jar or download
link:downloads.html[here].

Let's see code for conversion:

[source,groovy]
--
import org.grooscript.GrooScript

//Convert a fragment code
String jsResult = GrooScript.convert("println 'Hello!'")

//Convert some file or folder, generate .js files with same name.
GrooScript.convert('path/to/file/or/folder','path/to/destination/folder')

//And that's all, so easy make conversions
--

If you convert a file with dependencies to other files, you have to convert that files too.

=== Conversion Daemon

You can activate a daemon to convert your Groovy files when modify them.

[source,groovy]
--
import org.grooscript.GrooScript

//You can detect changes in files or files in folders. Sources can be a List of String or a String
def sources = ['src/groovy/presenters', 'myFile.groovy']
//Set destination of conversions, a folder or a .js file
def destination = 'js/gs.js'
//You can set conversion options, see below for options supported. Optional.
def options = [classpath:'src/groovy']

//The demon starts and converts all the files at start.
//Then listen, and each time any of the files changes, generate the new javascript file automatically.
//Read all files each second.
//Fourth parameter is an optional closure that will executes each time all read and converted. Optional.
//The closure receives a list with absolutePath of files modified
//Last parameter set recursion option, by default is false. If set to true, also folders will be converted.
def daemon = GrooScript.startConversionDaemon(sources, destination, options, { list -> list.each { println 'Converted file -> '+it}}, true)

//For stop the daemon
daemon.stop()
--

*** CONTINUE ***