= Roadmap http://grooscript.org[grooscript]
:author: Jorge Franco
:email: grooscript@gmail.com

The project started August 2012. Roadmap updated March 2015.

In 2015, will be working in this stuff:

=== Next major release 1.1

- At the moment, you have to convert files, folders or both. Target in this release is support package system, in javascript,
using http://requirejs.org/[require.js]. Grooscript will manage dependencies, convert necessary files, and generate
require.js modules to use them in web or node.js.

- Continue improving groovy support.

=== Grails plugin

- Version 1.0 with support for Grails 3. Support on tags and remote domain classes will be improved. Files conversion
and daemon support moved to gradle plugin. You can use both plugins in your grails 3 applications.

=== Gradle plugin

- Improve daemons to detect new created files and support require.js conversions.

As usual, you can contact me if you need something, ask questions or give me feedback.

++++
include::analytics.info[]
++++
