= Getting started with http://grooscript.org[grooscript] and gradle
:author: Jorge Franco
:email: grooscript@gmail.com
:source-highlighter: pygments
:icons: font

With grooscript, you can convert your groovy code to javascript. We will use http://www.gradle.org[gradle] to
create a static web project, with html file and some .js files. Application logic done in groovy, and run in the
browser because groovy code is converted to javascript.

Let's use https://github.com/chiquitinxx/grooscript-gradle-plugin[grooscript gradle plugin] to play with
grooscript. Install http://www.gradle.org[gradle] if you don't have it installed in your machine. You can use
http://gvmtool.net[Gvm] to install gradle 2.0. Is important you use gradle 2, because grooscript works with
groovy 2.0+. You can use older gradle versions, but gradle 1.x uses groovy 1.8, and you can have problems
converting code to javascript. After install gradle, just create a new folder and move to it.

=== Creating project

Create a +build.gradle+ file with the grooscript plugin data and gradle 2.0 wrapper. Is important you use gradle 2,
because grooscript works with groovy 2.0+. You can use older gradle versions, but gradle 1.x uses groovy 1.8, and
you can have problems converting code to javascript.

Install gradle if you don't have it installed in your machine. Run +> gradle wrapper+ to create gradlew executable.
Run +> ./gradlew task+ to see grooscript tasks.

Let's start with *initStaticWeb* task to create a html static project. Run +> ./gradlew initStaticWeb+ and the
plugin will create the following files.

[source,shell]
--
├── build.gradle
└── src
    └── main
        ├── groovy
        │   └── Presenter.groovy
        └── webapp
            ├── index.html
            └── js
                ├── app
                └── lib
                    ├── grooscript-all.js
                    └── jquery.min.js
--

Now, let's open index.html in your browser, for example running +> open src/main/webapp/index.html+ open my Google
Chrome. You must see an input text with label _Name:_ and a button _Say hello!_. If you put your name and
press button nothing happens, in javascript console you can see the error, a file called +Presenter.js+ not
found in +src/main/webapp/js/app+.

I introduced this error to show you that you have to convert your groovy code to javascript each time you
change your groovy files. We will see later that you can run a daemon to automatically convert your code when
a file change is detected. But for now, it's important that you understand that your groovy code isn't running
in your browser, the javascript converted code is. For convert your groovy code to javasscript,
run +> ./gradlew convert+ and a new javascipt file is generated, the missing file in the browser error.

[source,shell]
--
└── src
    └── main
        └── webapp
            └── js
                ├── app
                │   └── Presenter.js
--

Now, go the browser, reload the page, put your name and press _Say hello!_. The text +_Hello your_name!_+ will
be append to the page. So, nice, all is working, and the code that is running in your browser, is Groovy code.
The file +Presenter.groovy+ is a groovy file, that has been converted to javascript +Presenter.js+ with grooscript.
I have tested the groovy class with a spock test and I have used my favorite groovy IDE. This is one of the
reasons to use grooscript, you use the tools you know to create code that runs in your browser.

=== Playing

Now, let's take a look to +index.html+ code.

[source,html]
--
<html>
<head>
    <title>Initial static web page</title>
    <script type="text/javascript" src="js/lib/jquery.min.js"></script> //<1>
    <script type="text/javascript" src="js/lib/grooscript-all.js"></script> //<2>
    <script type="text/javascript" src="js/app/Presenter.js"></script> //<3>
</head>
<body>
    <p>Name:<input type="text" id="name"/></p> //<4>
    <input type="button" id="button" value="Say hello!"/> //<5>
    <div id="salutes"/> //<6>
    <script type="text/javascript">
        presenter = Presenter(); //<7>
        var binder = Binder(); //<8>
        $(document).ready(function() {
            binder.call(presenter); //<9>
            console.log('All binds done.');
        });
    </script>
</body>
--
<1> Grooscript itself doesn't requires jquery, but some of the tools in grooscript-all.js does.
<2> This js contains grooscript core and some tools to work with the DOM.
<3> This is the converted javascript code generated from Presenter.groovy.
<4> The input text with id _name_.
<5> The button with id _button_.
<6> The div where all salutes are added.
<7> Creation of the class, to create a class generated with grooscript, don't use _new_.
<8> Init the binder, a tool that comes in grooscript-all.
<9> Associate the binder with the presenter. Now _name_ input is binded to +presenter.name+ property. And when
you press the button, method +presenter.buttonClick()+ is executed.

Is very important, all code that you convert to javascript, using grooscript, it needs grooscript.js
lib. grooscript.js is included in grooscript-all.js, is the library that resolves the runtime of your
javascript code. If you take a look at +Presenter.js+ you will see some functions that starts with +gs.xxx+.
For example if you call a method, maybe the method doesn't exist, groovy is a dynamic language, and maybe at
runtime that method exists or not, or maybe there is a _methodMissing_ call. grooscript.js resolves method
calls, access to properties, java / groovy types,... so remember included it to run your javascript generated code.

Now, you can start to modify Presenter.groovy, much better if you create a Spock test for it. When you make a
change, remember that you have to generate the javascript code with +> ./gradlew convert+. So in a typical
grooscript workflow, you are working with your groovy code, and see the results in your browser, no class
loading issues, just reload the page with the changes in your javascript generated files. But is boring run
convert all the time, much better if you run +> ./gradlew daemon+. This daemon blocks execution of gradle,
and will listen changes in your groovy files. Each time a groovy file changes, groovy code will be converted
to javascript. Until you break gradle with ^C.

++++
include::analytics.info[]
++++
